"""Turn the generated CSVs into a portable 02_seed_data.sql (multi-row INSERTs)."""

import csv, os

BASE = os.path.join(os.path.dirname(__file__), "..")
DATA = os.path.join(BASE, "data")
OUT = os.path.join(BASE, "sql", "02_seed_data.sql")

NUMERIC = {"amount_dkk", "share_amount_dkk"}
BOOL = {"is_weekend", "is_payer"}
INT = {
    "person_id", "category_id", "expense_id", "share_id", "settlement_id",
    "paid_by_person_id", "from_person_id", "to_person_id", "year",
    "month_number", "day_of_month", "participant_count",
}

TABLES = [
    ("dim_person", "dim_person.csv"),
    ("dim_category", "dim_category.csv"),
    ("dim_date", "dim_date.csv"),
    ("fact_expense", "fact_expense.csv"),
    ("fact_expense_share", "fact_expense_share.csv"),
    ("fact_settlement", "fact_settlement.csv"),
]

CHUNK = 200


def lit(col, val):
    if col in INT or col in NUMERIC:
        return val
    if col in BOOL:
        return "TRUE" if val.lower() in ("true", "1") else "FALSE"
    return "'" + val.replace("'", "''") + "'"


with open(OUT, "w", encoding="utf-8") as out:
    out.write("-- =====================================================================\n")
    out.write("-- Seed data - generated by scripts/make_seed_sql.py (do not edit by hand)\n")
    out.write("-- Regenerate with:  python3 scripts/generate_data.py && python3 scripts/make_seed_sql.py\n")
    out.write("-- =====================================================================\n\n")
    out.write("SET search_path TO analytics;\n\n")

    for table, filename in TABLES:
        rows = list(csv.DictReader(open(os.path.join(DATA, filename), encoding="utf-8")))
        if not rows:
            continue
        cols = list(rows[0].keys())
        out.write(f"-- {table}: {len(rows)} rows\n")
        for i in range(0, len(rows), CHUNK):
            chunk = rows[i:i + CHUNK]
            out.write(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n")
            values = [
                "  (" + ", ".join(lit(c, r[c]) for c in cols) + ")"
                for r in chunk
            ]
            out.write(",\n".join(values) + ";\n")
        out.write("\n")

    out.write("ANALYZE;\n")

print(f"wrote {OUT} ({os.path.getsize(OUT):,} bytes)")
